AWSTemplateFormatVersion: "2010-09-09"
Description: Free Tier ETL - S3 + SNS + SQS + Lambdas

Parameters:
  ValidationLambdaRoleArn:
    Type: String
    Description: ARN of the IAM Role for Validation Lambda
  TransformationLambdaRoleArn:
    Type: String
    Description: ARN of the IAM Role for Transformation Lambda
  StepFunctionsRoleArn:
    Type: String
    Description: ARN of the IAM Role for Step Functions
  EventBridgeInvokeStepFunctionsRoleArn:
    Type: String
    Description: ARN of the IAM Role for EventBridge to invoke Step Functions

Resources:

  # --------------------
  # S3 Buckets
  # --------------------

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-free-tier-etl-raw-446072489762

  CuratedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-free-tier-etl-curated-446072489762

  # --------------------
  # SNS Topic
  # --------------------

  ETLTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: aws-free-tier-etl-topic

  # --------------------
  # SQS Queues + DLQ
  # --------------------

  ETLDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: aws-free-tier-etl-dlq

  ETLQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: aws-free-tier-etl-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ETLDLQ.Arn
        maxReceiveCount: 3

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ETLQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt ETLQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ETLTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ETLTopic
      Protocol: sqs
      Endpoint: !GetAtt ETLQueue.Arn

  # --------------------
  # Validation Lambda
  # --------------------

  ValidationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-free-tier-etl-validation
      Runtime: python3.10
      Handler: index.lambda_handler
      Role: !Ref ValidationLambdaRoleArn
      Timeout: 30
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref ETLTopic
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          sns = boto3.client("sns")
          TOPIC_ARN = os.environ["SNS_TOPIC_ARN"]

          def lambda_handler(event, context):
              record = event.get("record")
              if not record or "id" not in record:
                  sns.publish(
                      TopicArn=TOPIC_ARN,
                      Message=json.dumps({"status": "FAILED", "error": "Invalid record"})
                  )
                  raise ValueError("Invalid record")

              sns.publish(
                  TopicArn=TOPIC_ARN,
                  Message=json.dumps({"status": "SUCCESS", "record": record})
              )
              return {"status": "validated"}

  # --------------------
  # Transformation Lambda
  # --------------------

  TransformationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-free-tier-etl-transform
      Runtime: python3.10
      Handler: index.lambda_handler
      Role: !Ref TransformationLambdaRoleArn
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import boto3

          s3 = boto3.client("s3")
          CURATED_BUCKET = "aws-free-tier-etl-curated-446072489762"

          def lambda_handler(event, context):
              for record in event.get("Records", []):
                  body = json.loads(record["body"])
                  data = body.get("record", {})

                  output = {
                      "id": data.get("id"),
                      "processed": True
                  }

                  s3.put_object(
                      Bucket=CURATED_BUCKET,
                      Key=f"{output['id']}.json",
                      Body=json.dumps(output)
                  )

              return {"status": "done"}

  # --------------------
  # SQS → Lambda Wiring
  # --------------------

  TransformationLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TransformationLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt ETLQueue.Arn

  SQSToTransformationMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ETLQueue.Arn
      FunctionName: !Ref TransformationLambda
      BatchSize: 1
      Enabled: true

  # --------------------
  # Step Functions
  # --------------------

  ValidationStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: aws-free-tier-etl-validation-sm
      RoleArn: !Ref StepFunctionsRoleArn
      DefinitionString:
        Fn::Sub: |
          {
            "Comment": "ETL validation workflow",
            "StartAt": "ValidateData",
            "States": {
              "ValidateData": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${ValidationLambda.Arn}",
                  "Payload.$": "$"
                },
                "Retry": [
                  {
                    "ErrorEquals": ["Lambda.ServiceException", "Lambda.TooManyRequestsException"],
                    "IntervalSeconds": 2,
                    "MaxAttempts": 2,
                    "BackoffRate": 2
                  }
                ],
                "End": true
              }
            }
          }

  # --------------------
  # EventBridge Rule
  # --------------------

  ETLScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: aws-free-tier-etl-schedule
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !Ref ValidationStateMachine
          Id: StepFunctionsTarget
          RoleArn: !Ref EventBridgeInvokeStepFunctionsRoleArn
          Input: |
            {
              "record": {
                "id": "scheduled-run",
                "source": "eventbridge"
              }
            }
