AWSTemplateFormatVersion: "2010-09-09"
Description: Free Tier ETL - Base Infrastructure

Resources:

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-free-tier-etl-raw-446072489762

  CuratedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-free-tier-etl-curated-446072489762
