AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless ETL with Lambda validation, Glue transformation, Redshift target

Parameters:
  ProjectName:
    Type: String
    Default: aws-free-tier-etl

Resources:

# -------------------------------------------------
# S3 BUCKETS
# -------------------------------------------------

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-free-tier-etl-raw-446072489762

  CuratedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-free-tier-etl-curated-446072489762

# -------------------------------------------------
# SNS + SQS
# -------------------------------------------------

  ETLTopic:
    Type: AWS::SNS::Topic

  ETLDLQ:
    Type: AWS::SQS::Queue

  ETLQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ETLDLQ.Arn
        maxReceiveCount: 3

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref ETLQueue]
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt ETLQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ETLTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ETLTopic
      Protocol: sqs
      Endpoint: !GetAtt ETLQueue.Arn

# -------------------------------------------------
# VALIDATION LAMBDA
# -------------------------------------------------

  ValidationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ValidationPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: arn:aws:s3:::aws-free-tier-etl-raw-446072489762/*
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref ETLTopic
              - Effect: Allow
                Action: logs:*
                Resource: "*"

  ValidationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.10
      Handler: index.lambda_handler
      Role: !GetAtt ValidationLambdaRole.Arn
      Timeout: 60
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref ETLTopic
      Code:
        ZipFile: |
          import csv, io, json, boto3, os
          s3 = boto3.client("s3")
          sns = boto3.client("sns")
          REQUIRED_COLUMNS = ["email", "country"]

          def lambda_handler(event, context):
              bucket = event["bucket"]
              key = event["key"]
              obj = s3.get_object(Bucket=bucket, Key=key)
              reader = csv.reader(io.StringIO(obj["Body"].read().decode("utf-8")))
              rows = list(reader)

              header = rows[0]
              for col in REQUIRED_COLUMNS:
                  if col not in header:
                      raise ValueError(f"Missing column {col}")

              sns.publish(
                  TopicArn=os.environ["SNS_TOPIC_ARN"],
                  Message=json.dumps({
                      "bucket": bucket,
                      "key": key
                  })
              )
              return {"status": "validated"}

# -------------------------------------------------
# AWS GLUE (TRANSFORMATION)
# -------------------------------------------------

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GluePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::aws-free-tier-etl-raw-446072489762/*
                  - arn:aws:s3:::aws-free-tier-etl-curated-446072489762/*
              - Effect: Allow
                Action: logs:*
                Resource: "*"

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: aws-free-tier-etl-glue-job
      Role: !GetAtt GlueRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        ScriptLocation: s3://aws-free-tier-etl-curated-446072489762/scripts/glue_job.py
      DefaultArguments:
        --TempDir: s3://aws-free-tier-etl-curated-446072489762/temp/
        --job-language: python

# -------------------------------------------------
# STEP FUNCTIONS
# -------------------------------------------------

  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFnPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt ValidationLambda.Arn
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                Resource: "*"
              - Effect: Allow
                Action: logs:*
                Resource: "*"

  ETLStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString:
        Fn::Sub: |
          {
            "StartAt": "Validate",
            "States": {
              "Validate": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${ValidationLambda.Arn}",
                  "Payload.$": "$"
                },
                "Next": "Transform"
              },
              "Transform": {
                "Type": "Task",
                "Resource": "arn:aws:states:::glue:startJobRun.sync",
                "Parameters": {
                  "JobName": "aws-free-tier-etl-glue-job"
                },
                "End": true
              }
            }
          }

# -------------------------------------------------
# EVENTBRIDGE (SCHEDULING)
# -------------------------------------------------

  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EventBridgePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref ETLStateMachine

  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !Ref ETLStateMachine
          RoleArn: !GetAtt EventBridgeRole.Arn
          Id: ETLTarget
