AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Roles for Free Tier ETL

Resources:

  # --------------------
  # Validation Lambda IAM Role
  # --------------------

  ValidationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ValidationLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: arn:aws:s3:::aws-free-tier-etl-raw-446072489762/*
              - Effect: Allow
                Action: sns:Publish
                Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:aws-free-tier-etl-topic"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # --------------------
  # Transformation Lambda IAM Role
  # --------------------

  TransformationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TransformationLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: arn:aws:s3:::aws-free-tier-etl-curated-446072489762/*
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:aws-free-tier-etl-queue"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # --------------------
  # Step Functions IAM Role
  # --------------------

  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsInvokeLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:aws-free-tier-etl-validation"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # --------------------
  # EventBridge IAM Role
  # --------------------

  EventBridgeInvokeStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowStartExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:aws-free-tier-etl-validation-sm"

Outputs:
  ValidationLambdaRoleArn:
    Value: !GetAtt ValidationLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ValidationLambdaRoleArn"

  TransformationLambdaRoleArn:
    Value: !GetAtt TransformationLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-TransformationLambdaRoleArn"

  StepFunctionsRoleArn:
    Value: !GetAtt StepFunctionsRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StepFunctionsRoleArn"

  EventBridgeInvokeStepFunctionsRoleArn:
    Value: !GetAtt EventBridgeInvokeStepFunctionsRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EventBridgeInvokeStepFunctionsRoleArn"
